version: 1
formatters:
  simple:
    format: '%(asctime)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s'
  condensed:
    format: '%(name)s - %(funcName)s - %(levelname)s - %(message)s'
filters:
  numericalData:
    (): rove_comm_handler_numerical.NumericalDataFilter
handlers:
  console:
    class: logging.StreamHandler
    level: 0
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.WatchedFileHandler
    level: 0
    formatter: simple
    filename: example.log
    mode: a
    delay: False
  RoveCommUDP:
    class: rove_comm_handler.RoveCommHandler
    level: 0
    formatter: condensed
    target_host: 127.0.0.1
    target_port: 10999
  RoveCommTCP:
    class: rove_comm_handler_tcp.RoveCommHandlerTCP
    level: 0
    formatter: condensed
    target_host: 127.0.0.1
    target_port: 11112
  RoveCommNumerical:
    class: rove_comm_handler_numerical.RoveCommHandlerNumerical
    level: 0
    filters: [numericalData]
    target_host: 127.0.0.1
    target_port: 11112
loggers:
  my_lib:
    level: 0
    handlers: [RoveCommTCP, RoveCommNumerical]
root:
  level: 0
  handlers: [console, file]