version: 1
formatters:
  simple:
    format: '%(module)s, %(funcName)s, %(levelname)s, %(message)s'
  csv:
    format: '%(asctime)s.%(msecs)03d, %(module)s, %(funcName)s, %(levelname)s, %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  debug:
    format: "%(name)s, %(levelname)s, %(module)s, %(message)s %(pathname)s:%(lineno)d"
filters:
  numericalData:
    (): core.logging_filters.NumericalDataFilter
  debug:
    (): core.logging_filters.DebugFilter
handlers:
  console:
    class: logging.StreamHandler
    level: 0
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.WatchedFileHandler
    level: 0
    formatter: simple
    filename: logs/example.log
    mode: a
    delay: True
  csv:
    class: core.logging_handlers.CsvHandler
    level: 0
    formatter: csv
    format_string: TIMESTAMP MODULE FUNCTION LEVEL MESSAGE
    filename: logs/example.csv
    delay: False
  RoveCommUDP:
    class: core.logging_handlers.RoveCommHandlerUDP
    level: 0
    formatter: simple
    target_host: 127.0.0.1
    target_port: 10999
  RoveCommTCP:
    class: core.logging_handlers.RoveCommHandlerTCP
    level: 0
    formatter: simple
    target_host: 127.0.0.1
    target_port: 11112
  RoveCommNumerical:
    class: core.logging_handlers.RoveCommHandlerNumerical
    level: 0
    filters: [numericalData]
    target_host: 127.0.0.1
    target_port: 11112
  Debug:
    class: logging.StreamHandler
    level: DEBUG
    filters: [debug]
    formatter: debug
loggers:
  Logging_Test:
    level: DEBUG
    handlers: [RoveCommTCP, RoveCommNumerical, Debug]
root:
  level: DEBUG
  handlers: [console, csv]