name: Autonomy Unit Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-html pipenv
        pipenv install
        pipenv shell
    - name: Unit and coverage test with pytest
      run: |
        pytest --cov --html=report.html
    - name: Archive unit test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-report
        path: report.html

