name: Autonomy Unit Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d 
    - name: Checkout Submodules
      run: |
        git submodule update --init --recursive.
    - name: Unit and coverage test with pytest
      run: |
        pipenv run pytest -v --cov=../Autonomy_Software

